Models/ErrorViewModel.cs
using System;

namespace kien10engcnt.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ImageDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kien10engcnt.Models
{
    public class ImageDbContext : DbContext
    {
        public ImageDbContext(DbContextOptions<ImageDbContext> options)
            : base(options)
        {
        }

        public DbSet<ImageModel> Images { get; set; }
    }

    public class ImageContextFactory : IDesignTimeDbContextFactory<ImageDbContext>
    {
        public ImageDbContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ImageDbContext>();
            //optionsBuilder.UseSqlite("Data Source=images.db");

            return new ImageDbContext(optionsBuilder.Options);
        }
    }
}

Models/ImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace kien10engcnt.Models
{
    public class ImageModel
    {
        public string Id { get; set; }
        public string Url { get; set; }
        public string LocalPath { get; set; }
        public bool HasBeenModified { get; set; }

        public string Base64String { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using kien10engcnt.Models;

namespace kien10engcnt.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/School/SpeakingTopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using SixLabors.Primitives;
using SixLabors.Shapes;
using System.Net.Http;

namespace kien10engcnt.Controllers.School
{
    [Route("speaking_topics")]
    [Route("SpeakingTopics")]
    public class SpeakingTopicsController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/School/SpeakingTopics.cshtml");
        }
         
    }
}

Controllers/Utilities/ImageRotatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using kien10engcnt.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace kien10engcnt.Controllers.Utilities
{
    [Route("image")]
    public class ImageRotatorController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Views/Utilities/ImageRotator.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> Upload(ImageModel image)
        {
            image.Base64String = "data:image;base64," + await Utils.GetBase64StringAsync(image.Url);
            return View("~/Views/Utilities/ImageRotator.cshtml", image);
        }
        [HttpGet]
        [Route("{id}")]
        public IActionResult Rotate90Degrees(string id)
        {
            var imageModel = new ImageModel() { Id = id, LocalPath = $"{id}.jpg", HasBeenModified = true};
            var realPath = $"wwwroot\\{imageModel.LocalPath}";
            using (var image = Image.Load(realPath))
            {
                image.Mutate(ops =>
                {
                    ops.Rotate(RotateMode.Rotate90);
                });
                image.Save(realPath);
            }
            return View("~/Views/Utilities/ImageRotator.cshtml", imageModel);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1><hr />
    @*<input type="submit" value="Save" class="btn btn-default" />*@
    <!--
        <p>
        @Html.ActionLink("Sample", "Create",
            null, htmlAttributes: new { @class = "mybtn" })
    </p>

    <style type="text/css">
        a.mybtn {
            background: #2b2c2b;
            color: #ffffff;
            display: inline-block;
            padding: 6px 12px 6px 12px;
            text-decoration: none;
        }

    </style>
    -->

    <p>This website is still under construction, so please stay tune!</p>
</div>

Views/School/SpeakingTopics.cshtml
@{
    ViewData["Title"] = "Bài nói tuần này";
    var topics = Program.SpeakingTopics;

    int getRealTopicNumber()
    {
        var now = DateTimeOffset.UtcNow.ToOffset(new TimeSpan(7, 0, 0));
        var weeknum = Utils.GetIso8601WeekOfYear(now.DateTime);
        return weeknum + 6;
    }
    string getTopic(int num)
    {
        if (num >= Program.SpeakingTopics.Count) return "no topics found";
        var topic = Program.SpeakingTopics.ElementAt(num);
        return $"{num + 1}. {topic.Key} - {topic.Value}";
    }
    var topicNumber = getRealTopicNumber();
}
<h2>Bài nói tuần này là ...</h2>
<div>
    @getTopic(topicNumber - 2)
    <br>
    (theo như sự man trá của bạn Huyền Trần.)
</div>
<h2>
    nhưng nếu đúng ra thì chúng ta phải làm ...
</h2>
<div>
    @getTopic(topicNumber)
</div>
<hr />
<strong style="font-size:large">Danh sách toàn bộ topic</strong>
<ul>
    @for (int i = 0; i < topics.Count; i++)
    {
        var topic = topics.ElementAt(i);
        if (i == topicNumber || i == topicNumber - 2)
        {
            <li><span style="font-weight:bold">@($"{i + 1}. {topic.Key} - {topic.Value}")</span></li>
            continue;
        }
        <li>@($"{i + 1}. {topic.Key} - {topic.Value}")</li>
    }
</ul>
@*https://content.googleapis.com/drive/v3/files?q=%271DLhs1lskc3EmRBN4JSbhPjBSc8P_cmvZ%27%20in%20parents&key=AIzaSyAz-9o9q3fpJ7lpxU57pYVRh6t2rNOEBz8*@

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - kien10engcnt</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">kien10engcnt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                            -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - kien10engcnt
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Utilities/ImageRotator.cshtml
@model ImageModel
@{
    ViewData["Title"] = "Rotate Image";
}
<h1>Enter image URL</h1>
@*@using (Html.BeginForm("Upload", "ImageRotator", FormMethod.Post))
    {
        //<input id="url" name="Url" type="text" />
        @Html.TextBoxFor(x => x.Url);
        <input type="submit" value="Go!" class="btn btn-default" />
    }*@
<form asp-action="Upload" asp-controller="ImageRotator">
    <input asp-for="Url" class="form-control" />
    <input type="submit" value="Save" class="btn btn-primary" />
</form>
@if (!String.IsNullOrWhiteSpace(Model?.Base64String))
{
    <a asp-action="Rotate90Degrees" asp-controller="ImageRotator" asp-route-id="@Model.Id">Rotate right</a>

    <br />
    <img src="@Model.Base64String" alt="YOUR IMAGE HERE" />
}